apiVersion: v1
kind: Secret
metadata:
  name: {{ include "live-streaming-platform.fullname" . }}-secrets
type: Opaque
stringData:
{{- range $key, $value := .Values.global.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
