apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: platform-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: live-prod/jwt
    - secretKey: INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: live-prod/internal-service-token
    - secretKey: PLAYBACK_SIGNING_KEY
      remoteRef:
        key: live-prod/playback-signing
    - secretKey: INGEST_SIGNING_KEY
      remoteRef:
        key: live-prod/ingest-signing
