apiVersion: v1
kind: Service
metadata:
  name: mediamtx-rtmp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: mediamtx
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935
      protocol: TCP
