apiVersion: v1
kind: Service
metadata:
  name: mediamtx-webrtc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: mediamtx
  ports:
    - name: ice-udp
      port: 8189
      targetPort: 8189
      protocol: UDP
